### ISSUE TITLE
noise/image pairs

### ISSUE THREAD

**Issue by zhangyh33** [locuslab/get#1]
The noise image here is sampled from the Gaussian noise., or the real image after adding noise by T step?

**Comment by Gsunshine** [comment]
Hi @zhangyh33 ,

Thanks for your interest! That is a very good question! The noise-image pairs were sampled from the Gaussian noise rather than perturbed from the real images. 

Feel free to ask if you have further questions.

Zhengyang

**Comment by Gsunshine** [comment]
BTW, the FID scores shown in this repo were the distances to the test set, where popular distillation methods compute the FID to the train set. 

GET+Offline Distillation even rivals consistency distillation, if we take FID_train as the metric.  (For GET, usually FID_train ≈ FID_test - 2 on CIFAR10.) Offline Distillation is somewhat largely underestimated...

We'll update it later on. Please feel free to try GET!
