### ISSUE TITLE
Question about NFE of GET in Tab. 2

### ISSUE THREAD

**Issue by SeminKim** [locuslab/get#2]
Hi,
Thank you for sharing your excellent work!
I have a minor question regarding the experimental results presented in Table 2. Comparing with Fig.3(a), it seems that the GET model with NFE=1 uses several fixed point iterations (maybe 6?). Could you please confirm if this is correct?
Thanks in advance!

**Comment by Gsunshine** [comment]
Hi @SeminKim ,

Thanks for your interest in GET! For the results in Tab. 2, it uses 6 fixed point iters.

Cheers,
Zhengyang
